[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL
lib_deps = 
    bogde/HX711@^0.7.5
    knolleary/PubSubClient@^2.8
    madhephaestus/ESP32Servo
    https://github.com/tzapu/WiFiManager.git
